[package]
name = "catalog_reimpl"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = { workspace = true }
thiserror = { workspace = true }
catalog = { workspace = true }
blockly = { path = "../blockly/blockly", features = ["front"] }
