[package]
name = "dslgen"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = { workspace = true }
thiserror = { workspace = true }
serde = { workspace = true, features = ["derive"], optional = true }
lexer = { path = "../lexer", optional = true }
parser = { path = "../parser", optional = true }

[features]
default = ["lexer", "parser"]
with-serde = ["serde", "lexer/with-serde", "parser/with-serde"]
