[workspace]
resolver = "2"
members = [
    # Compiler
    "compiler/compiler",

    # Libirary
    "library/catalog/catalog",

    # Tools
    "src/editor/src-rs",

    # Examples
    "examples/calc_interpreter",
    "examples/minic_interpreter",
]
exclude = [
    # Doc-tools
    "src/rustdoc_web",

    # Tests
    "tests/default",
    "tests/with_serde",
]

[workspace.dependencies]
anyhow = "1.0.75"
thiserror = "1.0.50"
serde = "1.0.192"
compiler = { path = "compiler/compiler" }
catalog = { path = "library/catalog/catalog" }
