[package]
name = "blockdsl"
version = "0.1.0"
edition = "2021"

[dependencies]
compiler = { package = "compiler", path = "driver/compiler" }
interpreter = { package = "interpreter", path = "driver/interpreter" }
lib = { package = "lib", path = "library" }
processor = { package = "processor", path = "processor/processor" }

[dev-dependencies]
anyhow = "1.0"
thiserror = "1.0"
strum = { version = "0.25", features = ["derive"] }
blockdsl = { path = "./" }

[workspace]
members = [
    "builder",
    "driver/compiler",
    "driver/interpreter",
    "processor/processor",
    "library",
    "tests",
]
exclude = []

[[example]]
name = "calc_interpreter"
path = "examples/calculator/interpreter.rs"
