[workspace]
resolver = "2"
members = [
    # Compiler
    "compiler/compiler",

    # Catalog
    "catalog/catalog",

    # Tools
    "src/editor",
    "src/gen_template",

    # Examples
    "examples/calc_interpreter",
    "examples/minic_interpreter",
]
exclude = [
    # Docs
    "docs/web",

    # Tests
    "tests/default",
    "tests/with_serde",
]

[workspace.dependencies]
anyhow = "1.0.75"
thiserror = "1.0.50"
serde = "1.0.192"
