[package]
name = "blockdsl"
version = "0.1.0"
edition = "2021"

[dependencies]
compiler = { package = "compiler", path = "driver/compiler" }
interpreter = { package = "interpreter", path = "driver/interpreter" }
lib = { package = "lib", path = "library" }
processor = { package = "processor", path = "processor/processor" }

[workspace]
members = [
    "driver/compiler",
    "driver/interpreter",
    "processor/processor",
    "library",
    "tests",
    "examples",
]
exclude = []
