[workspace]
resolver = "2"
members = [
    # Compiler
    "compiler/compiler",

    # Library
    "library",

    # Examples
    "examples/calc_interpreter",

    # Tools
    # "tools/...",
]
exclude = []

[workspace.dependencies]
anyhow = "1.0.75"
thiserror = "1.0.50"
serde = "1.0.192"
