[workspace]
resolver = "2"
members = [
    # Compiler
    "compiler/compiler",

    # Library
    "library",

    # Examples
    "examples/simple_interpreter",
    "examples/calc_interpreter",

    # Tools
    # "tools/...",
]
exclude = []
