[package]
name = "constraint_ctime_declarative"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = { workspace = true }
thiserror = { workspace = true }

[dev-dependencies]
design = { path ="../../../design" }
