[package]
name = "entrypoint"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = { workspace = true }
thiserror = { workspace = true }
vfs = { workspace = true }
design = { path = "../../core/design" }
irgen = { path = "../../core/irgen" }
converter = { path = "./crates/converter" }
