[package]
name = "interpreter"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0"
thiserror = "1.0"
clap = { version = "4.3", features = ["derive"] }
processor = { path = "../../processor/processor" }
lib = { package = "lib", path = "../../library" }
