[package]
name = "catalog"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0"
thiserror = "1.0"
serde = "1.0"
compiler = { path = "../compiler/compiler" }
macros = { package = "catalog_macros", path = "./macros/macros" }
