[package]
name = "processor_dslgen"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0"
thiserror = "1.0"
lexer = { package = "processor_lexer", path = "../processor_lexer" }
parser = { package = "processor_parser", path = "../processor_parser" }
