[package]
name = "lib_runtime"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = { workspace = true }
thiserror = { workspace = true }
runtime_compiler = { package = "lib_runtime_compiler", path = "./crates/compiler" }
runtime_interpreter = { package = "lib_runtime_interpreter", path = "./crates/interpreter" }

