[package]
name = "lib"
version = "0.1.0"
edition = "2021"
publish = false

[dependencies]
anyhow = "1.0"
thiserror = "1.0"
strum = { version = "0.25", features = ["derive"] }
processor = { package = "processor", path = "../compiler/processor/processor" }
