[package]
name = "lib"
version = "0.1.0"
edition = "2021"

[dependencies]
catalog = { package = "lib_catalog", path = "./crates/catalog" }
runtime = { package = "lib_runtime", path = "./crates/runtime" }

