[package]
name = "runtime_macros"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = { workspace = true }
thiserror = { workspace = true }
procedural_macro = { package = "runtime_macros_procedural", path = "./crates/procedural" }
