[package]
name = "depagerpp_langpart"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0"
thiserror = "1.0"
regex = "1.9.1"
strum = { version = "0.25", features = ["derive"] }
itertools = "0.11"
