[package]
name = "compiler"
version = "0.1.0"
edition = "2021"

[dependencies]
designer = { path = "./crates/designer", optional = true }
processor = { path = "./crates/processor", optional = true }
exec_compiler = { path = "./crates/executor/compiler", optional = true }
exec_interpreter = { path = "./crates/executor/interpreter", optional = true }

[features]
default = ["processor", "exec_compiler", "exec_interpreter"]
build = ["designer"]
with-serde = ["designer/with-serde", "processor/with-serde"]
