[package]
name = "blockdsl_compiler"
version = "0.1.0"
edition = "2021"

[dependencies]
designer = { package = "designer", path = "designer/designer", optional = true }
processor = { package = "processor", path = "processor/processor", optional = true }
exec_compiler = { package = "compiler", path = "executor/compiler" }
exec_interpreter = { package = "interpreter", path = "executor/interpreter" }

[features]
default = ["designer", "processor"]
with-serde = ["designer/with-serde", "processor/with-serde"]
