[package]
name = "blockdsl_compiler"
version = "0.1.0"
edition = "2021"

[dependencies]
designer = { package = "designer", path = "designer/designer" }
processor = { package = "processor", path = "processor/processor" }
exec_compiler = { package = "compiler", path = "executor/compiler" }
exec_interpreter = { package = "interpreter", path = "executor/interpreter" }
