[package]
name = "compiler"
version = "0.1.0"
edition = "2021"

[dependencies]
# Core
designer = { path = "./crates/core/designer", optional = true }
processor = { path = "./crates/core/processor", optional = true }

# Interface (wrapper)
bricks = { path = "./crates/bricks", optional = true }
runtime = { path = "./crates/runtime", optional = true }

[features]
default = ["processor", "runtime"]
build = ["designer", "bricks"]
with-serde = ["designer/with-serde", "processor/with-serde"]
