[package]
name = "compiler"
version = "0.1.0"
edition = "2021"

[dependencies]
# Core
designer = { path = "./crates/core/designer", optional = true }
processor = { path = "./crates/core/processor", optional = true }

# Bricks
bricks = { path = "./crates/bricks", optional = true }

# Others
exec_compiler = { path = "./crates/executor/compiler", optional = true }
exec_interpreter = { path = "./crates/executor/interpreter", optional = true }

[features]
default = ["processor", "exec_compiler", "exec_interpreter"]
build = ["designer", "bricks"]
with-serde = ["designer/with-serde", "processor/with-serde"]
