[package]
name = "exec_compiler"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = { workspace = true }
thiserror = { workspace = true }
clap = { version = "4.3", features = ["derive"] }
processor = { path = "../../core/processor" }
