[package]
name = "rustdoc_web"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0"
thiserror = "1.0"
rocket = "0.5"
rustdoc = { package = "rustdoc_web_bundle", path = "./crates/rustdoc_bundle" }
