[package]
name = "utils_macros"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = { workspace = true }
thiserror = { workspace = true }
procedural_macros = { package = "utils_macros_procedural", path = "./crates/procedural" }
