[package]
name = "calc_interpreter"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = { workspace = true }
thiserror = { workspace = true }
compiler = { workspace = true }
lib = { workspace = true }

[build-dependencies]
compiler = { workspace = true }
lib = { workspace = true }
