[package]
name = "calc_interpreter"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0"
thiserror = "1.0"
compiler = { path = "../../compiler/compiler" }

[build-dependencies]
catalog = { path = "../../catalog/catalog" }
