[package]
name = "parser"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = { workspace = true }
thiserror = { workspace = true }
serde = { workspace = true, features = ["derive"] }
serde_json = "1.0"
itertools = "0.11"
lexer = { path = "../lexer", optional = true }
utils = { path = "../utils" }

[features]
default = ["lexer"]
with-serde = ["lexer/with-serde"]
