[package]
name = "ui"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = { workspace = true }
thiserror = { workspace = true }
tauri = { version = "1.5.3", features = ["api-all"] }

[build-dependencies]
tauri-build = "1.5.0"
blockly_front = { path = "./blockly/blockly_front" }
catalog = { package = "catalog_reimpl_blockly", path = "./catalog_reimpl" }
