[package]
name = "ui"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = { workspace = true }
thiserror = { workspace = true }
serde = { workspace = true, features = ["derive"] }
tauri = { version = "1.5.3", features = ["api-all"] }
blockly = { path = "./blockly/blockly", features = ["back"] }

[build-dependencies]
tauri-build = "1.5.0"
blockly = { path = "./blockly/blockly", features = ["front"] }
catalog = { package = "catalog_reimpl_blockly", path = "./catalog_reimpl" }
