[package]
name = "lib_runtime_interpreter"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = { workspace = true }
thiserror = { workspace = true }
compiler = { workspace = true, features = ["dev"] }
clap = { version = "4.3", features = ["derive"] }
crossterm = "0.27"

