[package]
name = "blockly"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = { workspace = true }
thiserror = { workspace = true }
blockly_front = { path = "../blockly_front", optional = true }
blockly_back = { path = "../blockly_back", optional = true }

[features]
default = []
all = ["blockly_front", "blockly_back"]
front = ["blockly_front"]
back = ["blockly_back"]
