[package]
name = "catalog_reimpl_blockly"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = { workspace = true }
thiserror = { workspace = true }
blockly = { path = "../blockly" }
catalog = { path = "../../../../../catalog/catalog" }
