[package]
name = "depagerpp"
version = "0.1.0"
edition = "2021"

[dependencies]
builder = { package = "depagerpp_builder", path = "../dpp_builder" }
macros = { package = "depagerpp_macros", path = "../dpp_macros" }
