[package]
name = "compiler_driver"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0"
thiserror = "1.0"
clap = { version = "4.3", features = ["derive"] }
langpart = { package = "compiler_langpart", path = "../compiler_langpart" }
