name: Release

on:
  push:
    branches:
    - "master"
  workflow_dispatch:

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    strategy:
      matrix:
        include:
          - os: windows
            ext: .exe
          - os: macos
            ext:
          - os: ubuntu
            ext:

    runs-on: ${{ matrix.os }}-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Install dependencies (Linux)
      if: matrix.os == 'ubuntu'
      run: |
        sudo apt update
        sudo apt install -y \
            libwebkit2gtk-4.0-dev \
            build-essential \
            curl \
            wget \
            file \
            libssl-dev \
            libgtk-3-dev \
            libayatana-appindicator3-dev \
            librsvg2-dev

    - name: Build tools
      run: |
        make -C src/editor setup
        cargo build --release --bin editor

    - name: Zip artifact (Windows)
      if: matrix.os == 'windows'
      run: |
        mkdir -p ${{ matrix.os }}
        cp target/release/editor${{ matrix.ext }} ${{ matrix.os }}
        Compress-Archive -Path ${{ matrix.os }}/* -DestinationPath ${{ matrix.os }}.zip

    - name: Zip artifact (Macos, Linux)
      if: matrix.os != 'windows'
      run: |
        mkdir -p ${{ matrix.os }}
        cp target/release/editor${{ matrix.ext }} ${{ matrix.os }}
        zip -r ${{ matrix.os }}.zip ${{ matrix.os }}

    - name: Upload artifact to release
      uses: svenstaro/upload-release-action@v2
      with:
        repo_token: ${{ secrets.GITHUB_TOKEN }}
        file: ${{ matrix.os }}.zip
        asset_name: ${{ matrix.os }}.zip
        release_name: x.x.x
        tag: latest

  cleanup:
    runs-on: ubuntu-latest

    needs: build

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Remove tags
      run: |
        git push origin :tags/latest
