name: Release Linux

on:
  push:
    branches:
    - "master"
  pull_request:
  workflow_dispatch:

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
    - uses: actions/checkout@v3

    - name: Install dependencies
      run:
        sudo apt update &&
        sudo apt install -y
            libwebkit2gtk-4.0-dev
            build-essential
            curl
            wget
            file
            libssl-dev
            libgtk-3-dev
            libayatana-appindicator3-dev
            librsvg2-dev

    - name: Build Editor
      run:
        make -C src/editor setup &&
        cargo build --release --bin editor

    - name: Upload artifact to release
      uses: svenstaro/upload-release-action@v2
      with:
        repo_token: ${{ secrets.GITHUB_TOKEN }}
        file: target/release/editor
        asset_name: editor
        draft: true
